import { useState, useMemo } from 'react';
import Head from 'next/head';
import BaseFooter from 'components/BaseFooter';
import styleNavbar from 'styles/components/navbar.module.sass';

interface Props extends React.HTMLAttributes<HTMLDivElement> {
  title?: string
}

export default function MainLayout({ title, children, ...props }: Props) {
  const [toggleMenu, setToggleMenu] = useState(true);
  const pageTitle = useMemo(() => [title, 'PKKMB UNS 2021'].filter(Boolean).join(' - '), [title]);

  return (
    <div
      className="bg-brand-2 shadow-lg flex flex-col items-center"
      {...props}
    >
      <Head>
        <title>{pageTitle}</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <nav className="fixed top-0 right-0 p-5">
        <button
          type="button"
          onClick={() => setToggleMenu(!toggleMenu)}
          className="h-10"
        >
          <div className={toggleMenu ? styleNavbar.hamburger : styleNavbar.hamburger_close} />
        </button>
      </nav>

      <main className="w-full max-w-screen-sm bg-white shadow-xl flex flex-col items-stretch">
        {children}
      </main>

      <BaseFooter className="max-w-screen-sm shadow-xl" />
    </div>
  );
}
